version: '3.9'

services:
  mysqldb:
    image: "mysql:8"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=abcde12345-
      - MYSQL_PASSWORD=abcde12345-
      - MYSQL_USER=admin
      - MYSQL_DATABASE=hectre_db
    volumes:
      - ./data:/var/lib/mysql
      #- ./conf/redis.conf:/etc/mysql/conf.d
      #restart: always  
    healthcheck:
      test:
        [
          "CMD",
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-p$$MYSQL_ROOT_PASSWORD'
        ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  backend:
    image: hectre-backend
    build:
      context: ./Backend/Hectre.BackEnd
      dockerfile: Hectre.BackEnd/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DemoMySqlConnection=server=mysqldb;uid=root;pwd=abcde12345-;database=hectre_db
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      mysqldb:
        condition: service_healthy
  frontend:
    image: hectre-frontend
    build:
      context: ./Frontend/hectre-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
